image:
  repository: your-image-repo/nextjs-app
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: nextjs.example.com
      paths: ["/"]