{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextjs-app.fullname" . }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 6 }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0] }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
